"""Journal encounters used by wish logic."""

JOURNAL_ENTRY = "Journal Entry"
JOURNAL_ENCOUNTERS = {
    'Aspid Collector': ('bone-bottom/the-big-fall', 'shellwood/shellwood-diddy-basement-tall-room', 'wormways/wormways-flea-rescue'),
    'Bell Fly': ('bellhart/bellhart-lower', 'bellhart/upper-bellhart'),
    'Bell Goomba': ('bellhart/bellhart-lower', 'bellhart/upper-bellhart'),
    'Blade Spider': ('sands-of-karak/sands-of-karak-entrance', 'whisp-thicket/wisp-thicket-cave', 'whispering-vaults/whispering-vaults-jumps'),
    'Blade Spider Hang': ('whisp-thicket/wisp-thicket-cave', 'whispering-vaults/whispering-vaults-jumps'),
    'Bloat Roach': ('bilewater/bilewater-lower-bloatroach-tower',),
    'Bloom Puncher': ('memorium/memorium-water-room', 'shellwood/cling-grip-room', 'shellwood/cling-grip-side-room', 'shellwood/shellwood-sister-splinter-bench'),
    'Bloom Shooter': ('memorium/memorium-water-room', 'memorium/seed-shooty-memorium', 'shellwood/shellwood-lower-left-tall-room'),
    'Bone Circler': ('bone-bottom/the-big-fall', 'deep-docks/deep-docks-bellway-flea-rescue', 'deep-docks/deep-docks-chains-west', 'far-fields/far-fields-pinstress-attic', 'far-fields/far-fields-pinstress-room', 'far-fields/far-fields-upper-shaft', 'memorium/memorium-rhino-room', 'the-marrow/the-marrow-lower-pogo', 'the-marrow/the-marrow-mr-burns-house', 'the-marrow/the-marrow-shaft', 'the-marrow/the-marrow-skull-wall'),
    'Bone Circler Vicious': ('far-fields/far-fields-bellway', 'far-fields/far-fields-pinstress-attic', 'far-fields/far-fields-pinstress-room', 'memorium/memorium-rhino-room'),
    'Bone Crawler': ('hunter-s-march/chapel-of-the-beast', 'memorium/memorium-rhino-room', 'the-marrow/the-marrow-flea-caravan', 'the-marrow/the-marrow-lower-pogo'),
    'Bone Flyer': ('memorium/memorium-rhino-room', 'the-marrow/the-marrow-entrance', 'the-marrow/the-marrow-skull-wall'),
    'Bone Goomba': ('deep-docks/deep-docks-spire-lower', 'memorium/memorium-rhino-room', 'the-marrow/the-marrow-entrance', 'the-marrow/the-marrow-lower-pogo', 'the-marrow/the-marrow-map-shop', 'the-marrow/the-marrow-mr-burns-house', 'the-marrow/the-marrow-skull-wall'),
    'Bone Goomba Large': ('deep-docks/deep-docks-bellway-flea-rescue', 'memorium/memorium-rhino-room', 'the-marrow/the-marrow-mr-burns-house', 'the-marrow/the-marrow-shaft', 'the-marrow/the-marrow-skull-wall'),
    'Bone Hopper': ('deep-docks/deep-docks-spire-lower',),
    'Bone Hunter': ('far-fields/far-fields-deep-entrance', 'far-fields/far-fields-deep-fort-passage', 'hunter-s-march/hunters-march-early-pathway-west'),
    'Bone Hunter Buzzer': ('hunter-s-march/hunters-march-pogo-intro',),
    'Bone Hunter Child': ('far-fields/far-fields-fort-flea-rescue', 'far-fields/far-fields-pinstress-attic'),
    'Bone Hunter Fly': ('far-fields/far-fields-deep-fort-passage',),
    'Bone Hunter Tiny': ('deep-docks/is-this-still-deep-docks-east', 'hunter-s-march/hunters-march-early-pathway-west', 'hunter-s-march/hunters-march-pogo-intro'),
    'Bone Roller': ('memorium/seed-shooty-memorium',),
    'Citadel Bat': ('bilewater/exhaust-organ-interior', 'high-halls/high-halls-flooded-room', 'high-halls/high-halls-small-room', 'the-slab/slab-infleatween-top', 'underworks/underworks-map-room', 'whiteward/whiteward-tunnel-room'),
    'Coral Conch Shooter': ('blasted-steps/blasted-steps-shakra-map-room', 'memorium/memorium-karak', 'sands-of-karak/crustnut'),
    'Coral Conch Shooter Heavy': ('memorium/memorium-karak', 'sands-of-karak/sands-of-karak-lower-left-long-room', 'sands-of-karak/sands-of-karak-lower-right-long-room', 'sands-of-karak/sands-of-karak-upper-left-long-room'),
    'Coral Conch Stabber': ('sands-of-karak/sands-of-karak-lower-right-long-room', 'sands-of-karak/sands-of-karak-right-side-tall-room', 'sands-of-karak/sands-of-karak-tall-centre-room', 'sands-of-karak/sands-of-karak-upper-right-long-room'),
    'Coral Goomba Large': ('memorium/memorium-karak',),
    'Coral Judge': ('blasted-steps/blasted-steps-shakra-map-room',),
    'Coral Spike Goomba': ('sands-of-karak/crustnut', 'sands-of-karak/sands-of-karak-elevator-to-blasted-steps', 'sands-of-karak/sands-of-karak-lower-left-long-room', 'sands-of-karak/sands-of-karak-lower-right-long-room'),
    'Coral Warrior Grey': ('sands-of-karak/watcher-at-the-edge',),
    'Crystal Drifter': ('mount-fay/brightvein', 'mount-fay/mount-fay-ice-lake-platforming-room', 'mount-fay/mount-fay-shakra'),
    'Crystal Drifter Giant': ('mount-fay/brightvein',),
    'Dock Bomber': ('deep-docks/deep-docks-chains-east', 'deep-docks/deep-docks-chains-west'),
    'Dock Charger': ('deep-docks/deep-docks-chains-center', 'deep-docks/deep-docks-chains-east'),
    'Dock Flyer': ('deep-docks/deep-docks-spool-east',),
    'Dock Worker': ('deep-docks/deep-docks-chains-center', 'deep-docks/deep-docks-chains-east', 'deep-docks/deep-docks-chains-west', 'deep-docks/deep-docks-spire-lower'),
    'Dustroach': ('sinner-s-road/sinner-s-road-muckroach-cages', 'sinner-s-road/sinner-s-road-north-hall'),
    'Farmer Catcher': ('greymoor/greymoor-halfway-home-exterior', 'greymoor/yarnaby-place'),
    'Farmer Centipede': ('greymoor/greymoor-middle-passage',),
    'Farmer Scissors': ('greymoor/greymoor-eastern-tower', 'greymoor/greymoor-western-room', 'greymoor/greymoor-western-tower'),
    'Fields Flock Flyers': ('far-fields/far-fields-deep-entrance', 'far-fields/far-fields-dock-loopback', 'far-fields/far-fields-fort-upper-passage', 'far-fields/far-fields-skull-room-east', 'far-fields/far-fields-skull-room-west', 'far-fields/far-fields-wind-shaft'),
    'Fields Flyer': ('deep-docks/deep-docks-chains-flea-rescue', 'far-fields/far-fields-deep-entrance', 'far-fields/far-fields-deep-fort', 'far-fields/far-fields-dock-loopback', 'far-fields/far-fields-entrance-west', 'far-fields/far-fields-fort-upper-passage', 'far-fields/far-fields-pinstress-attic'),
    'Fields Goomba': ('deep-docks/deep-docks-chains-flea-rescue', 'far-fields/far-fields-deep-docks-backdoor', 'far-fields/far-fields-deep-entrance', 'far-fields/far-fields-deep-fort-passage', 'far-fields/far-fields-deep-lower-west', 'far-fields/far-fields-dock-loopback', 'far-fields/far-fields-entrance-west', 'far-fields/far-fields-fort-flea-rescue', 'far-fields/far-fields-fort-upper-passage', 'far-fields/far-fields-pinstress-attic', 'far-fields/far-fields-pinstress-room', 'far-fields/far-fields-skull-room-east', 'far-fields/far-fields-skull-room-west', 'far-fields/far-fields-wind-shaft', 'far-fields/hunters-march-pilgrims-rest-deep-passage'),
    'Flower Drifter': ('memorium/seed-shooty-memorium', 'shellwood/cling-grip-room', 'shellwood/cling-grip-side-room', 'shellwood/shellwood-lower-left-tall-room', 'shellwood/shellwood-sister-splinter-bench'),
    'Gnat Giant': ('greymoor/greymoor-rat-tunnel',),
    'Mite': ('greymoor/greymoor-craw-lake', 'greymoor/greymoor-craw-lake-entrance', 'greymoor/greymoor-halfway-home-exterior', 'greymoor/greymoor-rat-tunnel', 'greymoor/greymoor-silver-shells-room', 'greymoor/greymoor-upper-halfway-home-path', 'greymoor/greymoor-upper-towers-path', 'greymoor/greymoor-west-bellshrine-room', 'greymoor/greymoor-western-room', 'greymoor/greymoor-western-tower', 'sinner-s-road/sinner-s-road-hanging-cages', 'sinner-s-road/sinner-s-road-muckroach-cages'),
    'Mite Heavy': ('choral-chambers/choral-chambers-below-spa', 'the-slab/slab-chilly-prison', 'the-slab/slab-flea-prison', 'underworks/underworks-crushing-path', 'underworks/underworks-saw-shaft', 'underworks/underworks-wisp-thicket-passage'),
    'Mitefly': ('greymoor/greymoor-halfway-home-exterior', 'greymoor/greymoor-rat-tunnel', 'greymoor/greymoor-silver-shells-room', 'greymoor/greymoor-towers-patio', 'greymoor/greymoor-upper-halfway-home-path', 'greymoor/greymoor-upper-towers-path'),
    'MossBone Crawler': ('memorium/memorium-mossy', 'memorium/memorium-start-shaft', 'moss-grotto/moss-grotto-east', 'moss-grotto/moss-grotto-west'),
    'MossBone Crawler Fat': ('memorium/memorium-mossy',),
    'MossBone Fly': ('memorium/memorium-bench', 'memorium/memorium-start-shaft', 'moss-grotto/moss-grotto-center', 'moss-grotto/moss-grotto-west'),
    'Peaks Drifter': ('mount-fay/mount-fay-lower-slope', 'mount-fay/mount-fay-mask-shard', 'mount-fay/mount-fay-right-side-middle-room', 'mount-fay/mount-fay-upper-slope'),
    'Pilgrim 01': ('the-marrow/the-marrow-lower-pogo', 'the-marrow/the-marrow-mr-burns-house'),
    'Pilgrim 01 Song': ('choral-chambers/choral-chambers-above-ventrica',),
    'Pilgrim 02': ('far-fields/far-fields-skull-room-east',),
    'Pilgrim 02 Song': ('choral-chambers/choral-chambers-flea-shaft',),
    'Pilgrim 03': ('greymoor/greymoor-lower-halfway-home-path', 'the-marrow/the-marrow-mr-burns-house'),
    'Pilgrim 03 Song': ('choral-chambers/choral-chambers-flea-shaft',),
    'Pilgrim 03 Understore': ('underworks/underworks-crushing-path', 'underworks/underworks-east-shaft', 'underworks/underworks-lava-flow-corridor', 'underworks/underworks-lever-spike-corridor', 'underworks/underworks-saw-intro'),
    'Pilgrim 04': ('far-fields/far-fields-skull-room-east', 'wormways/wormways-flea-rescue'),
    'Pilgrim 04 Song': ('choral-chambers/choral-chambers-flea-shaft',),
    'Pilgrim Bellthrower Fly': ('blasted-steps/blasted-steps-shakra-map-room', 'shellwood/shellwood-far-left-tall-room', 'wormways/wormways-shaft'),
    'Pilgrim Fisher': ('shellwood/shellwood-big-room-left', 'shellwood/shellwood-left-side-long-pond-room'),
    'Pilgrim Fly': ('the-marrow/the-marrow-lower-pogo', 'wormways/wormways-shaft'),
    'Pilgrim Hiker': ('blasted-steps/blasted-steps-shakra-map-room',),
    'Pilgrim Moss Spitter': ('wormways/wormways-flea-rescue',),
    'Pilgrim Staff Understore': ('underworks/underworks-central-shaft', 'underworks/underworks-crushing-path', 'underworks/underworks-lava-flow-corridor'),
    'Pilgrim StaffWielder': ('greymoor/greymoor-upper-halfway-home-path',),
    'Pilgrim Stomper Song': ('choral-chambers/choral-chambers-flea-shaft',),
    'Pond Skater': ('memorium/memorium-water-room', 'shellwood/shellwood-big-room-left', 'shellwood/shellwood-diddy-basement-main', 'shellwood/shellwood-left-side-long-pond-room', 'shellwood/shellwood-right-side-big-room', 'shellwood/shellwood-top-room'),
    'Roachfeeder Short': ('greymoor/greymoor-upper-towers-path', 'sinner-s-road/sinner-s-road-hanging-cages'),
    'Roachfeeder Tall': ('sinner-s-road/sinner-s-road-hanging-cages',),
    'Roachkeeper': ('sinner-s-road/sinner-s-road-north-hall',),
    'Scholar': ('whispering-vaults/whispering-vaults-below-bench',),
    'Scrollkeeper': ('whispering-vaults/whispering-vaults-below-bench',),
    'Shell Fossil Mimic': ('greymoor/greymoor-silver-shells-room', 'sands-of-karak/sands-of-karak-elevator-to-blasted-steps'),
    'Shellwood Wasp': ('shellwood/shellwood-big-room-left',),
    'Shield Dock Worker': ('deep-docks/deep-docks-chains-east',),
    'Slab Fly Large': ('the-slab/slab-chilly-top',),
    'Slab Fly Mid': ('the-slab/slab-cell', 'the-slab/slab-flea-prison', 'the-slab/slab-infleatween-top'),
    'Slab Fly Small': ('the-slab/slab-infleatween-bottom',),
    'Slab Prisoner Fly New': ('the-slab/slab-chilly-prison', 'the-slab/slab-indolent-room'),
    'Slab Prisoner Leaper New': ('the-slab/slab-chilly-prison', 'the-slab/slab-indolent-room', 'the-slab/slab-infleatween-bottom'),
    'Song Administrator': ('high-halls/high-halls-big-shaft', 'high-halls/high-halls-big-slide', 'high-halls/high-halls-shaft-bottom', 'high-halls/high-halls-shaft-top'),
    'Song Automaton Fly': ('choral-chambers/choral-chambers-east-to-west',),
    'Song Creeper': ('whiteward/whiteward-descent-connection',),
    'Song Pilgrim 01': ('choral-chambers/choral-chambers-above-ventrica',),
    'Song Pilgrim 03': ('choral-chambers/choral-chambers-above-ventrica', 'the-slab/slab-bridge'),
    'Song Pilgrim Maestro': ('high-halls/high-halls-big-slide',),
    'Song Reed': ('choral-chambers/choral-chambers-above-ventrica', 'the-slab/slab-bridge'),
    'Spine Floater': ('far-fields/far-fields-skull-room-east', 'far-fields/far-fields-skull-room-west'),
    'Stick Insect': ('shellwood/shellwood-big-room-left', 'shellwood/shellwood-hidden-bellhart-connection'),
    'Stick Insect Charger': ('shellwood/shellwood-big-room-left', 'shellwood/shellwood-flower-pogo-upper-hall'),
    'Swamp Barnacle': ('putrified-ducts/putrified-ducts-entrance',),
    'Swamp Drifter': ('bilewater/bilewater-bullshit-bench', 'bilewater/bilewater-citadel-exit', 'bilewater/bilewater-mothleaf-hall', 'bilewater/bilewater-spike-ball-ceiling-trap-room', 'bilewater/bilewater-upper-west-column'),
    'Swamp Ductsucker': ('putrified-ducts/putrified-ducts-entrance',),
    'Swamp Goomba': ('bilewater/bilewater-east-column', 'bilewater/bilewater-hanging-corpse-room', 'bilewater/bilewater-lower-bloatroach-tower', 'bilewater/bilewater-lower-east-hall-secret', 'bilewater/bilewater-organ-entrance', 'bilewater/bilewater-sinner-s-entrance', 'bilewater/bilewater-west-secret-rooms'),
    'Swamp Mosquito': ('bilewater/bilewater-east-column', 'bilewater/bilewater-organ-entrance', 'bilewater/bilewater-sinner-s-entrance', 'bilewater/bilewater-spike-ball-ceiling-trap-room', 'bilewater/bilewater-west-secret-rooms'),
    'Swamp Mosquito Skinny': ('putrified-ducts/putrified-ducts-entrance',),
    'Tar Slug': ('deep-docks/deep-docks-chains-center', 'deep-docks/deep-docks-chains-west', 'deep-docks/deep-docks-lower-west-shaft', 'deep-docks/deep-docks-magma-slug-tunnels'),
    'Tar Slug Huge': ('deep-docks/deep-docks-magma-slug-tunnels',),
    'Understore Automaton': ('underworks/underworks-craftmetal-corridor', 'underworks/underworks-east-shaft', 'underworks/underworks-lava-flow-corridor'),
    'Understore Automaton EX': ('underworks/underworks-craftmetal-corridor', 'underworks/underworks-east-shaft', 'underworks/underworks-flea-room', 'underworks/underworks-lava-flow-corridor'),
    'Understore Heavy': ('underworks/underworks-craftmetal-corridor', 'underworks/underworks-shard-room'),
    'Understore Mite Giant': ('high-halls/high-halls-cogfly-room', 'high-halls/high-halls-flooded-room', 'whispering-vaults/whispering-vaults-below-bench', 'whiteward/whiteward-descent'),
    'Understore Poker': ('underworks/underworks-central-shaft', 'underworks/underworks-clawline-room', 'underworks/underworks-crushing-path', 'underworks/underworks-silk-spool'),
    'Understore Small': ('underworks/underworks-lever-spike-corridor', 'underworks/underworks-rosary-room'),
    'Understore Thrower': ('underworks/underworks-central-shaft', 'underworks/underworks-craftmetal-corridor', 'underworks/underworks-rosary-room', 'underworks/underworks-silk-spool'),
    'Weaver Servitor': ('bilewater/bilewater-weavenest-murglin', 'far-fields/weavenest-cindril-entrance'),
    'Weaver Servitor Large': ('mount-fay/mount-fay-large-servitor-hallway', 'mount-fay/mount-fay-shakra'),
}
